version: '3.8'


services:

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - pgdb_data:/var/lib/postgresql/data/
    ports:
        - '5439:5432'
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      interval: 4s
      retries: 10

volumes:
  pgdb_data:


