# Generated by Django 4.1.7 on 2023-07-09 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tguser",
            name="id",
        ),
        migrations.RemoveField(
            model_name="tguser",
            name="user_ud",
        ),
        migrations.RemoveField(
            model_name="tguser",
            name="username",
        ),
        migrations.AlterField(
            model_name="tguser",
            name="chat_id",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
